# Generated by Django 5.2.7 on 2025-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='videos/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
